#pragma config(Motor,  port2,           SpinMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           ClawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           frontmotorR,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           frontmotorL,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           backmotorR,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           backmotorL,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(1 == 1)
	{
		if(vexRT[Btn8R] == 1)
		{
			motor(SpinMotor) = 50;
			wait1Msec(100);
		}
		else
		{
			stopMotor(SpinMotor);
		}
		if(vexRT[Btn8L] == 1)
		{
			motor(SpinMotor) = -50;
			wait1Msec(100);
		}
		else
		{
			stopMotor(SpinMotor);
		}
		if(vexRT[Btn8U] == 1)
		{
			motor(ClawMotor) = 50;
			wait1Msec(100);
		}
		else
		{
			stopMotor(ClawMotor);
		}
		if(vexRT[Btn8D] == 1)
		{
			motor(ClawMotor) = -50;
			wait1Msec(100);
		}
		else
		{
			stopMotor(ClawMotor);
		}
		if(vexRT[Btn6D] == 1)
		{
			motor(frontmotorR) = -120;
			motor(frontmotorL) = 120;
			motor(backmotorR) = -120;
			motor(backmotorL) = 120;
			wait1Msec(100);


		}
		else
		{
			stopMotor(frontmotorR);
			stopMotor(frontmotorL);
			stopMotor(backmotorR);
			stopMotor(backmotorL);
		}
		if(vexRT[Btn5D] == 1)
		{
			motor(frontmotorR) = 120;
			motor(frontmotorL) = -120;
			motor(backmotorR) = 120;
			motor(backmotorL) = -120;
			wait1Msec(100);


		}
		else
		{
			stopMotor(frontmotorR);
			stopMotor(frontmotorL);
			stopMotor(backmotorR);
			stopMotor(backmotorL);
		}
		if(vexRT[Btn6U] == 1)
		{
			motor(frontmotorR) = 80;
			motor(frontmotorL) = 80;
			motor(backmotorR) = 80;
			motor(backmotorL) = 80;
			wait1Msec(100);
		}
		else
		{
			stopMotor(frontmotorR);
			stopMotor(frontmotorL);
			stopMotor(backmotorR);
			stopMotor(backmotorL);
		}
		if(vexRT[Btn5U] == 1)
		{
			motor(frontmotorR) = -80;
			motor(frontmotorL) = -80;
			motor(backmotorR) = -80;
			motor(backmotorL) = -80;
			wait1Msec(100);
		}
		else
		{
			stopMotor(frontmotorR);
			stopMotor(frontmotorL);
			stopMotor(backmotorR);
			stopMotor(backmotorL);
		}






	}

}
