#pragma config(Motor,  port2,           SpinMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           ClawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           frontmotorR,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           frontmotorL,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           backmotorR,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           backmotorL,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1 == 1)
	{
		if(vexRT[Btn8R] == 1)
		{
			motor(SpinMotor) = 80;
		}
		else
		{
			stopMotor(SpinMotor);
		}
		if(vexRT[Btn8L] == 1)
		{
			motor(SpinMotor) = -50;
		}
		else
		{
			stopMotor(SpinMotor);
		}
		if(vexRT[Btn8U] == 1)
		{
			motor(ClawMotor) = 80;
		}
		else
		{
			stopMotor(ClawMotor);
		}
		if(vexRT[Btn8D] == 1)
		{
			motor(ClawMotor) = -50;
		}
		else
		{
			stopMotor(ClawMotor);
		}
		if(vexRT[Btn6D] == 1)
		{
			motor(frontmotorR) = 127;
			motor(frontmotorL) = 127;
			motor(backmotorR) = -127;
			motor(backmotorL) = 127;
		}
		else
		{
			stopMotor(frontmotorR);
			stopMotor(frontmotorL);
			stopMotor(backmotorR);
			stopMotor(backmotorL);
		}
		if(vexRT[Btn5D] == 1)
		{
			motor(frontmotorR) = -127;
			motor(frontmotorL) = -127;
			motor(backmotorR) = 127;
			motor(backmotorL) = -127;
		}
		else
		{
			stopMotor(frontmotorR);
			stopMotor(frontmotorL);
			stopMotor(backmotorR);
			stopMotor(backmotorL);
		}
	}

}
